# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'tkinter',
        'tkinter.messagebox',
        'tkinter.simpledialog',
        'sqlite3',
        'json',
        'threading',
        'datetime',
        'hashlib',
        'hmac',
        'secrets',
        're',
        'os',
        'sys',
        'pathlib',
        'dotenv',
        'openai',
        'google.genai',
        'google.genai.types',
        'agent',
        'llm',
        'auth',
        'history',
        'database',
        'cases',
        'evidence',
        'memory',
        'detective',
        'persona',
        'tools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'test_provider_switch',
        'test_chat_history',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AgentKafle',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

app = BUNDLE(
    exe,
    name='AgentKafle.app',
    icon=None,
    bundle_identifier='com.agentkafle.agentkafle',
    info_plist={
        'CFBundleName': 'AgentKafle',
        'CFBundleDisplayName': 'AgentKafle',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '10.13',
    },
)
